//UserName: ben
//V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.03-Fork1\RTC_P4_WDT_Example_V1.00.03-Fork1.cydsn\SCRIPT
//UserDomain: DP7510590YYF2
//ComputerName: DP7510590YYF2
//logFile: V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.03-Fork1\RTC_P4_WDT_Example_V1.00.03-Fork1.cydsn\SCRIPT\2020-10-27_03-09-15-24_ben-build.h
//logTime: 2020-10-27_03-09-15-24
///* THIS FILE IS AUTO GENERATED BY THE PreBuildScript.ps1 DO NOT MODIFY!!!!*/
#define TIME_HOUR_BUILD           (0x03u)
#define TIME_MIN_BUILD            (0x09u)
#define TIME_SEC_BUILD            (0x15u)
#define HOUR_OFFSET_BUILD         (16u)
#define MIN_OFFSET_BUILD          (8u)
#define DATE_MONTH_BUILD          (RTC_OCTOBER)
#define DATE_DAY_BUILD            (0x27u)
#define DATE_YEAR_BUILD           (0x2020u)
#define MONTH_OFFSET_BUILD        (0u)
#define DAY_OFFSET_BUILD          (0u)
/* [] END OF FILE */
