$cComment ="//"
$cDeffine ="#define "
$BuildDate = Get-Date

$logTime = "$((Get-Date).ToString('yyyy-MM-dd_HH-mm-ss-ff'))"
$logUser = "$ENV:UserName"
#$logURL = $logTime + "_" + $logUser + "-build.h"
$logURL = "FirmwareBuildTime.h"
#echo $logURL
$relativeDIR = Get-Location
#$logFile = "V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.03-Fork1\SCRIPT\$logURL-build.txt"
$logFile =  Join-Path $relativeDIR  -ChildPath $logURL
#$destination = Split-Path -Path $relativeDIR -Parent
#$logFile =  Join-Path $destination  -ChildPath $logURL
#echo $logFile
#$logFile = "V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.03-Fork1\RTC_P4_WDT_Example_V1.00.03-Fork1.cydsn\FirmwareBuildTime.h"


$cComment + "UserName: " + $env:UserName > $logFile
$cComment + $relativeDIR >> $logFile
$cComment + "UserDomain: " + $env:UserDomain >> $logFile
$cComment + "ComputerName: " + $env:ComputerName >> $logFile
$cComment + "logFile: " + $logFile >> $logFile
$cComment + "logTime: " + $logTime >> $logFile
$cComment + "/* THIS FILE IS AUTO GENERATED BY THE PreBuildScript.ps1 DO NOT MODIFY!!!!*/" >> $logFile

<#
#define TIME_HOUR_BUILD           (0x02u)
#define TIME_MIN_BUILD            (0x59u)
#define TIME_SEC_BUILD            (0x50u)
#define HOUR_OFFSET_BUILD         (16u)
#define MIN_OFFSET_BUILD          (8u)



                            


/* Date: 2020-10-03 */

#define DATE_MONTH_BUILD          (RTC_OCTOBER)
#define DATE_DAY_BUILD            (0x03u)
#define DATE_YEAR_BUILD           (0x2020u)
#define MONTH_OFFSET_BUILD        (0u)
#define DAY_OFFSET_BUILD          (0u)
%B
#>

$cDeffine + "TIME_HOUR_BUILD           (0x" + $BuildDate.ToString('HH') + "u)" >> $logFile
$cDeffine + "TIME_MIN_BUILD            (0x" + $BuildDate.ToString('mm') + "u)" >> $logFile
$cDeffine + "TIME_SEC_BUILD            (0x" + $BuildDate.ToString('ss') + "u)" >> $logFile
$cDeffine + "HOUR_OFFSET_BUILD         (16u)"   >> $logFile
$cDeffine + "MIN_OFFSET_BUILD          (8u)"    >> $logFile



                            


#/* Date: 2020-10-03 */

$cDeffine + "DATE_MONTH_BUILD          (RTC_" + $BuildDate.ToString('MMMM').ToUpper() + ")" >> $logFile
$cDeffine + "DATE_DAY_BUILD            (0x" + $BuildDate.ToString('dd') + "u)" >> $logFile
$cDeffine + "DATE_YEAR_BUILD           (0x" + $BuildDate.ToString('yyyy') + "u)" >> $logFile
$cDeffine + "MONTH_OFFSET_BUILD        (24u)" >> $logFile
$cDeffine + "DAY_OFFSET_BUILD          (16u)" >> $logFile

"/* [] END OF FILE */">> $logFile
(Get-Content $logFile) | Set-Content $logFile -Encoding UTF8