//UserName: ben
//V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.04-Fork1\RTC_P4_WDT_Example_V1.00.04-Fork1.cydsn
//UserDomain: DP7510590YYF2
//ComputerName: DP7510590YYF2
//logFile: V:\Dynaris-V\Psoc-Sleep_Docks\2020-10-14_Testing\RTC_P4_WDT_Example_V1.00.04-Fork1\RTC_P4_WDT_Example_V1.00.04-Fork1.cydsn\FirmwareBuildTime.h
//logTime: 2020-10-27_09-14-59-26
///* THIS FILE IS AUTO GENERATED BY THE PreBuildScript.ps1 DO NOT MODIFY!!!!*/
#define TIME_HOUR_BUILD           (0x09u)
#define TIME_MIN_BUILD            (0x14u)
#define TIME_SEC_BUILD            (0x59u)
#define HOUR_OFFSET_BUILD         (16u)
#define MIN_OFFSET_BUILD          (8u)
#define DATE_MONTH_BUILD          (RTC_OCTOBER)
#define DATE_DAY_BUILD            (0x27u)
#define DATE_YEAR_BUILD           (0x2020u)
#define MONTH_OFFSET_BUILD        (24u)
#define DAY_OFFSET_BUILD          (16u)
/* [] END OF FILE */
